services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance_backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - attendance_network

  frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - attendance_network

networks:
  attendance_network:

