version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: attendance_mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=Attendances
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db                # dùng đúng tên volume bạn muốn
      - ./backup:/backup
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - attendance_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin123
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    networks:
      - attendance_network

  frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - attendance_network

volumes:
  mongodb_data:             # đúng tên volume mong muốn

networks:
  attendance_network:
